
import sys
import sqlite3
from PyQt5 import QtCore, QtGui, QtWidgets
import test

class Ui_MainWindow(object):
    def calc_price(self):
        pass
    

    def get_data(self,texts):
        text=self.lineEdit.text()
         
        self.text=text
        connection=sqlite3.connect('hen.db')
        mycursor=connection.cursor()
        self.connection=connection
        self.mycursor=mycursor
        try:    
            self.mycursor.execute('SELECT *FROM GOODS WHERE ITEM_NO=:itm_num',{'itm_num':int(self.text)})
            self.load_data()
        finally:
            print(mycursor.fetchall())            
            self.lineEdit.setText('')
            self.connection.close() 
    
    def load_data(self):
      
        self.mycursor.execute('SELECT *FROM GOODS WHERE ITEM_NO=:itm_num',{'itm_num':int(self.text)})
        result = self.mycursor.fetchall()
       
        try:
            
            numRows = self.tableWidget.rowCount()
            self.tableWidget.insertRow(numRows)
            print(numRows)
                
            for column_number in range(4):
                self.data=result[0]               
                self.tableWidget.setItem(numRows,column_number,QtWidgets.QTableWidgetItem(str(self.data[column_number])))
                print(numRows)
        except:
                print(sys.exc_info()[0])
                
               

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(798, 600)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(7)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(160, 0, 531, 561))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.frame.setFont(font)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(20, 20, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.cusname = QtWidgets.QLineEdit(self.frame)
        self.cusname.setGeometry(QtCore.QRect(160, 20, 281, 20))
        self.cusname.setObjectName("cusname")
        self.radioButton = QtWidgets.QRadioButton(self.frame)
        self.radioButton.setGeometry(QtCore.QRect(160, 330, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.radioButton.setFont(font)
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.frame)
        self.radioButton_2.setGeometry(QtCore.QRect(240, 330, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.frame)
        self.radioButton_3.setGeometry(QtCore.QRect(310, 330, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.radioButton_3.setFont(font)
        self.radioButton_3.setObjectName("radioButton_3")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(20, 330, 131, 31))
        self.label_3.setObjectName("label_3")
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setGeometry(QtCore.QRect(0, 360, 541, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.frame)
        self.line_2.setGeometry(QtCore.QRect(0, 320, 531, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(60, 50, 81, 20))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.emailid = QtWidgets.QLineEdit(self.frame)
        self.emailid.setGeometry(QtCore.QRect(160, 50, 281, 20))
        self.emailid.setObjectName("emailid")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(60, 380, 121, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.total = QtWidgets.QLabel(self.frame)
        self.total.setGeometry(QtCore.QRect(180, 380, 221, 21))
        self.total.setText("")
        self.total.setAlignment(QtCore.Qt.AlignCenter)
        self.total.setObjectName("total")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(60, 410, 121, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(60, 440, 121, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.received = QtWidgets.QLabel(self.frame)
        self.received.setGeometry(QtCore.QRect(180, 410, 221, 21))
        self.received.setText("")
        self.received.setAlignment(QtCore.Qt.AlignCenter)
        self.received.setObjectName("received")
        self.change = QtWidgets.QLabel(self.frame)
        self.change.setGeometry(QtCore.QRect(180, 440, 221, 21))
        self.change.setText("")
        self.change.setAlignment(QtCore.Qt.AlignCenter)
        self.change.setObjectName("change")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        
        self.pushButton.setGeometry(QtCore.QRect(160, 490, 161, 31))
        self.pushButton.setObjectName("pushButton")
        
        self.tableWidget = QtWidgets.QTableWidget(self.frame)
        self.tableWidget.setGeometry(QtCore.QRect(10, 110, 521, 211))
        self.tableWidget.setRowCount(0)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(40, 80, 71, 21))
        self.label_2.setObjectName("label_2")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(270, 80, 71, 21))
        self.label_8.setObjectName("label_8")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(100, 80, 151, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_2.setGeometry(QtCore.QRect(300, 80, 113, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(424, 80, 91, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.get_data)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 798, 17))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "CUSTOMER NAME :"))
        self.radioButton.setText(_translate("MainWindow", "CASH"))
        self.radioButton_2.setText(_translate("MainWindow", "CARD"))
        self.radioButton_3.setText(_translate("MainWindow", "NETBANKING"))
        self.label_3.setText(_translate("MainWindow", "MODE OF PAYMENT"))
        self.label_4.setText(_translate("MainWindow", "EMAIL ID:"))
        self.label_5.setText(_translate("MainWindow", "TOTAL:"))
        self.label_6.setText(_translate("MainWindow", "RECEIVED:"))
        self.label_7.setText(_translate("MainWindow", "CHANGE:"))
        self.pushButton.setText(_translate("MainWindow", "GENERATE INVOICE"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ITEM NO"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "NAME"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "QTY"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "RATE"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "PRICE"))
        self.label_2.setText(_translate("MainWindow", "ITEM NO."))
        self.label_8.setText(_translate("MainWindow", "QTY"))
        self.pushButton_2.setText(_translate("MainWindow", "ENTER"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
